### PR TITLE
feat: support GraphQL syntax highlighting

### PR DESCRIPTION
**Pull request by sarahs**
👋 This PR adds GraphQL syntax highlighting using https://github.com/dpeek/highlightjs-graphql.

Happy to make changes if there's a better way to do this.

cc @marshallofsound @dpeek @zeke

### CODE REVIEW

**Comment by zeke** [comment]
I just pulled down this branch and the tests are passing for me on Node 12, but failing on Node 8 (though with a [different but similar error](https://gist.github.com/zeke/7fa0a2b307ebfa874784338b79b9cb42)).

Maybe we need to update `.circleci/config.yml` to use Node 12 instead of 8 (for tests) and 10 (for releases)?

**Comment by zeke** [comment]
I'm able to reproduce the CircleCI error with `rm -rf node_modules && yarn && npm t`

Not sure why this doesn't work with yarn, despite the yarn.lock file being updated 🤔 

cc @electron/wg-ecosystem

**Comment by MarshallOfSound** [comment]
Hey @sarahs looks like a few dependencies needed updating to support whatever new syntax this PR utilizes.  I pushed those updates to this branch 👍

**Comment by zeke** [comment]
@sarahs for the record, this is how @MarshallOfSound said he ironed out the lockfile issues:

> `yarn upgrade-interactive` gives you a handy UI to update deps

**Pull request merged**
