### PR TITLE
Add markdown footnotes parsing

### PR DESCRIPTION
**Pull request by sofianguy**
fix for [this](https://github.com/electron/electron/issues/12085) issue

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for jumping on this, @sofianguy!

The test you've added proves that links like `[foo]` are working. That's good to know.

It looks like all the links mentioned in https://github.com/electron/electron/issues/12085 are actually using a format like `[ready-to-use templates][forge-templates]` where the first block is the link text, and the second block is the keyword that corresponds to a URL at the bottom of the file. Apparently this is the first use of this kind of markdown syntax in the Electron docs.

@wooorm, you wrote remark and [remark-inline-links](https://ghub.io/remark-inline-links). Do you know of a module that supports this extended link format? If not, should we try to add support for it in `remark-inline-links`?

**Comment by zeke** [comment]
From the [CommonMark spec](http://spec.commonmark.org/0.28/#full-reference-link)

> There are three kinds of reference links: full, collapsed, and shortcut.

> A shortcut reference link consists of a link label that matches a link reference definition elsewhere in the document and is not followed by [] or a link label. 

> A full reference link consists of a link text immediately followed by a link label that matches a link reference definition elsewhere in the document.

**Comment by wooorm** [comment]
These are called reference-style links, footnotes in markdown are usually a reference to content ([such as this](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#optionsfootnotes)).

Reference links come in three flavours: `[foo]`, `[foo][]`, and `[foo][bar]`. In the last case, a definition `[bar]: example.com` is needed, in the first two, `[foo]: example.com`. The first case does not create a link if the definition is not given, but the second and third one do.

remark should support all these cases, so [`remark-inline-links`](https://github.com/remarkjs/remark-inline-links) should work. Are you saying it doesn’t?

**Comment by zeke** [comment]
Sorry for the unnecessary ping, @wooorm. False alarm!

I thought full reference links were not working, but they are. Here's a test: https://github.com/electron/hubdown/pull/3/commits/54ab76ddda3263f1f09235dda1306a89c49c12a4

Looks like the issue stems from elsewhere in the Electron website pipeline.

**Comment by wooorm** [comment]
No problem Zeke! 👍

**Pull request merged**
